model-bakers/model_bakery

README.rst

Fixed the pypi badge

---

docs/source/index.rst

Add a more detailed explanation on the reasos for the rename

---

tests/conftest.py
tests/generic/models.py
tests/test_baker.py

This PR just increases our test coverage to ensure #51 is not a real issue.
Fixes #51.

Add tests to ensure batch creation works fine with _quantity parameter

---

CHANGELOG.md
docs/source/recipes.rst
model_bakery/utils.py
tests/generic/baker_recipes.py
tests/test_recipes.py

Add start parameter to baker.seq method

---

docs/source/index.rst

This PR introduces 2 minor suggestions in our docs index page.

Minor docs suggestions

---

setup.py

Tested since PR model-bakers/model_bakery#48

Add trove classifier for Python 3.8

---

.github/workflows/changelog.yml

https://github.com/peterjgrainger/action-changelog-reminder

Add a changelog reminder

---

.github/workflows/changelog.yml
.github/workflows/tests.yml
CHANGELOG.md
README.md
docs/source/index.rst
docs/source/migrating_from_mommy.rst

Replace master branch by main

---

CHANGELOG.md
docs/source/index.rst
docs/source/test_runners.rst

Hi, attempting #14. Any thoughts?

Add pytest usage example

---

CHANGELOG.md
docs/source/index.rst
docs/source/test_runners.rst

Follow up to #121 - as it was merged to `master` branch instead of `main`.
I also added review comment from here: https://github.com/model-bakers/model_bakery/pull/121#pullrequestreview-516052457

Add pytest usage example (#121)

---

docs/source/recipes.rst

Adds documentation to address #132

Add documentation that seq can query the database

---

README.md

"So long, and thanks for all the fish".

Stepping down as maintainer

---

docs/source/basic_usage.rst

Added documentation for callables, iterables, sequences.

Issue #27 - Added documentation for callables, iterables, sequences

---

.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/tests.yml
CHANGELOG.md
setup.py
tox.ini

- https://docs.python.org/3.11/
- https://docs.djangoproject.com/en/dev/releases/4.1/

Add Python 3.11, Django 4.1 support

---

CHANGELOG.md
model_bakery/baker.py
model_bakery/random_gen.py
model_bakery/recipe.py
tests/conftest.py
tests/test_extending_bakery.py
tests/test_filling_fields.py
tests/test_recipes.py

Convert string interpolations and format to f-strings.

convert string interpolations and format to f-strings

---

CHANGELOG.md
tox.ini

test Python 3.11 with Django 4.2

---

.github/workflows/ci.yml
.gitignore
CHANGELOG.md
pyproject.toml
tox.ini

Setting the border to 97% for now, will increase to 100% as soon as I'll fix the coverage.

Add test coverage

---

CHANGELOG.md
pyproject.toml
tox.ini

https://docs.djangoproject.com/en/5.0/releases/5.0/
Django 5.0 supports Python 3.10, 3.11, and 3.12

Support Django 5.0

---

CHANGELOG.md
pyproject.toml
tox.ini

In this pull request, I'm trying to confirm support for Django 5.2
#525 

Add Django 5.2 support

---

.github/workflows/ci.yml
tox.ini

ci: run test with github action matrix

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
pyproject.toml
tox.ini

https://docs.python.org/3.14/whatsnew/3.14.html

Add Python 3.14 support
