model-bakers/model_bakery

- utils/from_mommy_to_bakery.py
I was happy to see there is a script to help with the mommy -> baker migration, great idea!
However when I tried migrating the `from_mommy_to_bakery.py` stumbled over our `.gitignore` that included lines like:
```gitignore
htmlcov/
.tox/
nosetests.xml
coverage.xml
.cov/
```
The trailing slash on some of these resulted in the directory list not being filtered down as expected, thus `.tox` etc. were fully scanned. Removing the trailing slashes fixed that for me.
I've also taken the freedom to do a tiny change and avoid modifying the module global `exclude` and instead mark it as constant `EXCLUDE` and work on a copy within `check_files()`, I hope that wasn't too bold.
> Fix .gitignore line like '.tox/' not properly excluded in script

- .pre-commit-config.yaml
- model_bakery/__init__.py
- model_bakery/baker.py
- model_bakery/generators.py
- model_bakery/random_gen.py
- model_bakery/recipe.py
- model_bakery/timezone.py
- model_bakery/utils.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_utils.py
This PR is an attempt of making the comments stick to a style. We're considering to adopt Google's docstrings but open to suggestions as usual.
```
D100: Missing docstring in public module
D103: Missing docstring in public function
D101: Missing docstring in public class
D107: Missing docstring in __init__
D102: Missing docstring in public method
```
> Improve code comments

- .travis.yml
- tox.ini
Our previous approach did not run flake8 job (which later will be extended with other linters and checkers).
This is an attempt to cover that issue.
> Use Travis Jobs for build matrix

- .travis.yml
- tox.ini
This PR adds official Travis package, called `tox-travis` (https://tox-travis.readthedocs.io/en/stable/) to simplify test suite.
Previously we defined complicated matrix in travis config to run all possible version and service variations we have. Now this package handles all that, we only need to specify which python versions to run against. This looks much cleaner and simpler to maintain.
Also, now it uses **3 jobs instead of 14**, which reduces running time from **~11 minutes down to ~4 minutes**.
Total run time reduced from **~27 minutes to ~11 minutes**.
Linting tasks are running under python 3.6 environment since version does not really matter here (instead of having expensive separate job).
And I need to mention a small positive bug fix that I accidentaly made here. PostgreSQL tests …
> Switch to tox-travis

- .travis.yml
- CHANGELOG.md
- docs/source/index.rst
- tox.ini
Fix #45
This PR:
- Adds Django 3.0 and Python 3.8 to Travis CI
- Updates Postgres version on Travis (PG 10, postgis 2.5)
- Switches Travis CI from xenial to bionic (Ubuntu 18.04)
- Removes obsolete `before_install` commands
- Removes Python 3.5 as Django 3.0 does not support it (I don't think we need to support this version)
- Updates changelog with all changes since 1.0.2
> Add Django 3.0 and Python 3.8 to CI

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/generators.py
- tests/conftest.py
- tests/generic/fields.py
- tests/generic/models.py
- tests/test_filling_fields.py
Fixes #18 
The many comments on #18 describes why this work was required, but the short summary is that [the instruction in the docs](https://model-bakery.readthedocs.io/en/latest/how_bakery_behaves.html#custom-fields) to set generators for custom fields via `settings.py` wasn't working. Django raises the exception `AppRegistryNotReady` if the code tries to import anything related to the DB before properly creating the models.
Model bakery wasn't respecting this rule because it was importing the `ContentType` model and a few `django.contrib.gis` models too. This PR fixes this by replacing direct imports by module's imports and by moving others imports to be done during the execution time.
> Fix error when adding custom fields generators to bakery via settings file

- CHANGELOG.md
- model_bakery/generators.py
- model_bakery/random_gen.py
I think 10000 is just too low. 
We have been having flakyness in our tests with UNIQUE constraints on Integer columns because of conflicting values we this generator.
> Increase default randomness for integer generators

- model_bakery/generators.py
The result of `generators.get_type_mapping()` is being used when registering types in `baker.init_type_mapping`, but the return value of `get_type_mapping` is being set to the copied value of the mappings _before_ postgis models have been added.  This leads model baker to believe that the PostGis models are invalid, when in fact, they are valid.
Given this model in `myapp/models.py`...
```
from django.contrib.gis.db import models as gis_models
from django.db import models
class MyModel(models.Model):
point = gis_models.PointField(srid=4326)
```
The code below errors when executed in the Django shell:
```
from model_bakery import baker
instance = baker.make(MyModel)
```
with the following error: `TypeError: <class 'django.contrib.gis.db.models.fields.PointField'> is not supported by …
> Fixes PostGIS model registration

- docs/source/how_bakery_behaves.rst
There is a small typo in docs/source/how_bakery_behaves.rst.
Should read `specifying` rather than `specifing`.
> docs: Fix simple typo, specifing -> specifying

- CHANGELOG.md
- docs/source/recipes.rst
- model_bakery/baker.py
- tests/test_baker.py
- tests/test_recipes.py
Enable the seq() function to be imported from the baker module like
it is in the recipe module so that it can be used as baker.seq() if
preferred or to avoid namespace issues.
The current import can be left in place for backwards compatibility
or to continue importing seq as before.
Closes #75
> Enable seq to be imported from baker

- .pre-commit-config.yaml
- CHANGELOG.md
- Makefile
- docs/source/conf.py
- model_bakery/baker.py
- model_bakery/gis.py
- model_bakery/random_gen.py
- model_bakery/recipe.py
- model_bakery/utils.py
- setup.cfg
- setup.py
- tests/generic/baker_recipes.py
- tests/generic/forms.py
- tests/generic/models.py
- tests/generic/tests/sub_package/baker_recipes.py
- tests/test_baker.py
- tests/test_extending_bakery.py
- tests/test_filling_fields.py
- tests/test_recipes.py
- tests/test_utils.py
- tox.ini
- updated pre-commit
- added isort to pre-commit and tox (config compatible with black)
- fixed imports
- fixed some docstrings to comply with pydocstring
- added some missing asserts in tests
Better reviewed commit by commit.
> Update pre-commit, add isort and fix imports

- CHANGELOG.md
- dev_requirements.txt
- docs/source/how_bakery_behaves.rst
- model_bakery/baker.py
- model_bakery/generators.py
- model_bakery/gis.py
- model_bakery/random_gen.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_filling_fields.py
- tox.ini
Fixes #70 
Fixes #81 
This PR add supports to [Postgres's range fields](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#range-fields).
> Add support to postgres range fields

- docs/source/how_bakery_behaves.rst
> Add `FloatRangeField` to list of supported fields in docs

- CONTRIBUTING.md
- Makefile
- README.md
- docs/source/index.rst
- model_bakery/random_gen.py
- tests/conftest.py
- tests/generic/models.py
This PR is a result from a comment in #85 from @xi about issues with `black` and with running the tests. So, this PRs updates:
1. The test code to not break with default `python -m pytest` command because it uses a SQLite DB;
2. Introduces a `make lint` command which matches the specs from our CI;
3. Move the `Contributing` section from our documetation to our repository README;
@amureki can you review this one for me? If you're ok with that, feel free to merge and I'll release a new model bakery's version.
> Improve contributing instructions and utilitaries

- dev_requirements.txt
- model_bakery/baker.py
- tox.ini
There seem to be a conflict between isort and black even with compatible configuration:
https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines
I did not dig deep, but fixing a comment helps here, so this feels good enough to me. :)
> Bring isort back to CI

- CHANGELOG.md
- model_bakery/generators.py
- tests/generic/models.py
- tests/test_filling_fields.py
see https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends
> add support for django 3.1 JSONField

- CHANGELOG.md
- tests/generic/models.py
- tests/test_filling_fields.py
Fixing tests import to match [generators.py#L50](https://github.com/model-bakers/model_bakery/blob/master/model_bakery/generators.py#L50):
```python
try:
from django.db.models import JSONField
except ImportError:
JSONField = None
```
> Fix JSONfield test import

- CHANGELOG.md
- docs/source/recipes.rst
Minor correction.
In the recipe docs [here](https://model-bakery.readthedocs.io/en/latest/recipes.html#recipes-with-foreign-keys),
I suppose `customer` should be `owner` for 'PurchaseHistory' recipe
going by the description below which says "You may be thinking: 'I can put the Customer model instance directly in the owner field'"
> Correct field in recipe docs

- CHANGELOG.md
- model_bakery/generators.py
- tests/generic/models.py
- tests/test_filling_fields.py
- tox.ini
`django.contrib.postgres.fields.FloatRangeField` has been removed in Django 3.1, see https://docs.djangoproject.com/en/3.1/releases/3.1/#features-removed-in-3-1
> Fix compatibility with Django 3.1 and actually run test against it

- CHANGELOG.md
- README.md
- docs/source/basic_usage.rst
- docs/source/recipes.rst
- model_bakery/utils.py
- tests/test_recipes.py
This change introduces the ability to append a common suffix on to values generated by `seq`.
Fixes #93 
Some fields may represent data that generally contains a common suffix, like in the case of emails. Mock data is therefore differentiated in the first portion of the field's value. An example of this:
```
fake.user1@example.com
fake.user2@example.com
...
```
By allowing an optionally supplied suffix, the `seq` function is able to append some common string onto its generated values.
A `suffix` keyword argument was added to the `seq` function to allow the concatenation of a common suffix string onto a generated value. This will not work with types of `value` other than `str`. Tests have been added to cover the "happy" and some "sad" path use of the new keyword argument.
Example: …
> Add support for `suffix` in `seq` (fix #93)

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/recipe.py
This fixes `_model` argument annotation in a few places where it can be either a class or str (I'm not sure whether it would be better to create an alias).
> Fix _model annotation

- .github/workflows/tests.yml
- CHANGELOG.md
- setup.py
- tox.ini
Python 3.5 did reach end-of-life in September 2020:
https://www.python.org/downloads/release/python-3510/
We can safely remove it from our test environment to reduce test running time.
> Drop retired Python 3.5

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_extending_bakery.py
This change fixes #116, the following bug:
> If a field is of a class that does not have a generator (default or provided by the user) also has a `default` value which is a callable, the generated value is returned as the callable, not the result of calling the same.
For instance:
```python
from django.db import models
from model_bakery import baker
class MyField(models.TextField):
pass
class DummyModel(models.Model):
test = MyField(default=lambda: "default value")
dummy = baker.make(DummyModel)
dummy.test  # <function <lambda> at 0x7f0eadb9dca0>
dummy.test  # "default value"
```
This also addresses the fact that the `default` value for a field was not always being returned from `Baker.generate_value` since it was lower in the `if, elif, else` block which also checked for the generator …
> [116] Support Callable `default` and Always Use `default` If Present

- CHANGELOG.md
- CONTRIBUTING.md
- postgis-tests.sh
- tests/conftest.py
Fixes #107.
Instructions for running `postgres` and `postgis` tests locally have been added to `CONTRIBUTING.md`. The instructions explain a way to run the tests against a database that is run using `docker`.
A script, `postgis-tests.sh`, has been added to do the heavy lifting for the user (once the dependencies have been installed). It may be desired to turn that into a `make` target in the future.
This provides a clean and reproduceable way to run the `postgres` and `postgis` specific tests locally.
Follow the instructions in the `CONTRIBUTING.md` file. Comment on this PR if anything does not work or is missing.
> [107] Add Instructions and Script To Run `postgis` Tests

- CHANGELOG.md
- model_bakery/recipe.py
- model_bakery/utils.py
- tests/test_recipes.py
- tests/test_utils.py
This change set allows a caller of `foreign_key` to supply a recipe via a `str` value that refers to a recipe from another module. Up to now, if a `str` value was passed in to `foreign_key` it would attempt to load that recipe in the module from which `foreign_key` was called. That functionality is still present. It is used as a fallback if the `str` value provided does not refer to a recipe from another module.
Fixes #52.
This offers more flexibility to the use of `foreign_key` and does not require the caller to import the recipe that they want to use.
The code for `foreign_key`, `RecipeForeignKey`, and `related` was refactored slightly to reduce code duplication for the logic of loading a recipe from the "calling module". In addition to that, since it is assumed that most users of …
> [52] Allow string values for `foriegn_key` from other modules

- CHANGELOG.md
- docs/source/basic_usage.rst
- model_bakery/baker.py
- model_bakery/random_gen.py
- model_bakery/recipe.py
- tests/conftest.py
- tests/generic/baker_recipes.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_recipes.py
- tox.ini
Fixes #94
This PR introduces the new parameter `_using` to baker API so callers can specify which database they want to use. If no value, it uses django's default DB.
This PR was created during Python Brasil 2020 with the amazing help from @flavioamieiro @rhenanbartels @mazulo @berrondo
> Enable multi-database support

- CHANGELOG.md
- model_bakery/recipe.py
@berinhard Here is a PR for the issue :)
> #124: Corrected type hint for recipe param "_model"

- .github/workflows/tests.yml
This would prevent the error `E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler73_0.62.0-2ubuntu2.10_amd64.deb  404  Not Found [IP: 52.250.76.244 80]`.
https://github.community/t/sudo-apt-install-fails-with-failed-to-fetch-http-security-ubuntu-com-404-not-found-ip/17075
> Update packages before installing it

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_baker.py
- This enables the use of `bulk_create` for the models that are
created with `_quantity` supplied. This could offer performance
advantages when creating large quantities of data.
- It works by instead "preparing" the models and supplying them
to the `_base_manager.bulk_create`.
Fixes #65
> [#65] Add `_bulk_create` parameter to `make`

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/utils.py
- tests/test_recipes.py
- tests/test_utils.py
If the reasoning in #139 makes sense (yep, it might not), this is a draft for the fix.
Locally I had to create `tests/__init__.py` to run tests, is that expected?
> Allows import_from_str to import from inputs like app_name.ModelName 

- CHANGELOG.md
- model_bakery/__about__.py
- model_bakery/__init__.py
- model_bakery/utils.py
- setup.py
- tox.ini
While working on #141 I found out that we are importing the whole `model_bakery` lib just in order to obtain `__version__`.
And due to the change in imports, tox starts to fail.
```
Run python -m tox
GLOB sdist-make: /home/runner/work/model_bakery/model_bakery/setup.py
ERROR: invocation failed (exit code 1), logfile: /home/runner/work/model_bakery/model_bakery/.tox/log/GLOB-0.log
================================== log start ===================================
Traceback (most recent call last):
File "setup.py", line 5, in <module>
import model_bakery
File "/home/runner/work/model_bakery/model_bakery/model_bakery/__init__.py", line 8, in <module>
from .utils import seq  # NoQA
File "/home/runner/work/model_bakery/model_bakery/model_bakery/utils.py", line 16, in <module>
from .timezone …
```
> Modify `setup.py` to not import the whole module for package data

- CHANGELOG.md
- model_bakery/__about__.py
- model_bakery/__init__.py
- model_bakery/random_gen.py
- model_bakery/timezone.py
- setup.py
- tests/generic/baker_recipes.py
- tests/test_recipes.py
- tox.ini
I decided to do smaller steps to tackle #35 :)
It should be simpler to review-iterate now.
P.S. I wonder if this should be considered as a breaking change, but I doubt anyone who switched to `model_bakery` was using Django 1.4 and was importing this method.
P.P.S. Tests did fail due to the `setup.py` import issue. I put a separate PR for them: https://github.com/model-bakers/model_bakery/pull/142 and rebased this one on top of that branch. So the only meaningful here is the first commit: 2ec3eacc1a22b25d10034dc3f46b81377f3d384d. To simplify review, I changed base branch to `about`, which will be switched to `main` automatically after #142 would be merged.
> Drop obsolete `model_bakery.timezone.now`

- CHANGELOG.md
- tests/test_utils.py
Previously, we only tested it within recipe tests.
I decided to put a dedicated unit-test, which also directly covers `USE_TZ` setting.
> Add a unit test for `utils.seq`

- CHANGELOG.md
- model_bakery/timezone.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_utils.py
- remove `smart_datetime` (replaced by direct `tz_aware` use)
- update module docstrings, remove TODO comment
Current base is `test_seq` to be sure `seq` functions as before.
> Timezone module cleanup

- .github/dependabot.yml
- CHANGELOG.md
- Monitor GitHub Actions package ecosystem
- Auto-rebase dependabot PRs in case of conflicts with `main` branch
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
> Update Dependabot config file to support GH Actions and auto-rebase

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_filling_fields.py
https://github.com/model-bakers/model_bakery/pull/117 introduced an issue for two cases :
- where `id` value is provided as default for foreign key
- where foreign key is defaulting to `None`, but we overwrite this default by some value
See discussion in #136 that led to a current solution (first fix attempt was different, see 035281c0b07f88bfdac8375460f41495070cc7de).
This PR attempts to fix that issue by checking if the field has a default AND not overwritten in `self.rel_fields`.
I've added test cases, kindly suggested by @cb109 in #136.
> Fix creation of model instances with related model fields

- .github/workflows/release.yml
- CHANGELOG.md
Adds an automated action based on GitHub releases to simplify PyPI release process.
> [dev] Add Github Actions for package releasing

- CHANGELOG.md
- docs/source/recipes.rst
- model_bakery/recipe.py
- tests/generic/baker_recipes.py
- tests/test_recipes.py
Fixes #145 by adding an `one_to_one` argument to `foreign_key` and documents the behaviour.
When `one_to_one=True`, the `make_recipe` function will create an unique related model for each `_quantity`. This is False by default so the behaviour where only one related model is created remains the default.
Thanks for all the 🍰 😄
> Allows _quantity use on recipes containing OneToOne fields (#145)

- CHANGELOG.md
- model_bakery/generators.py
- tests/test_filling_fields.py
To match with currently supported Django versions (2.2+).
> Add explanations to imports in `generators.py`

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/baker_recipes.py
- tests/test_baker.py
- tests/uninstalled/baker_recipes.py
Fixes #192.
Using @Arussil's suggestion from the same referenced issue, added unit tests to cover the bug case and existing behavior.
> Fix Recipe Import Bug from Non-Installed-App Module

- CHANGELOG.md
- docs/source/recipes.rst
Fixes #211.
Addresses a couple of typos in a note on the Recipes documentation page.
> [issue/211] Fix docs typos on `recipes.rst`

- CHANGELOG.md
- docs/source/basic_usage.rst
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_baker.py
- tests/utils.py
Fixes #202 
@amureki and @anapaulagomes please take a read before on Djangos `bulk_create` docs and you'll understand more the context behind this PR:
https://docs.djangoproject.com/en/3.0/ref/models/querysets/#bulk-create
Short summary: Django does not update the created objects via bulk and, because of that, there no way to avoid subsequent `save` calls on related objects. I've implemented with recursion because the same is true for the related of the related objects =}
> _bulk_create flag is now creating related objects as well

- CHANGELOG.md
- model_bakery/baker.py
This adds proper typing for enabling at least PyCharm to support proper code completion and silence type warnings in `baker.make` and `baker.prepare` calls.
1. Before, PyCharm was always complaining about the first parameter to `baker.make` not being of `Type[ModelBase]`, which is correct, as we're passing derived models, not the `ModelBase`.
2. Before, PyCharm was unable to provide code completion for the resulting instance. Although this is still not perfect because of the `_quantity` parameter, it now correctly lists fields and methods for the passed model class besides the `list` interface. I.e., we do not need to write `mocked_model: SomeModel = baker.make(SomeModel)` every time, and instead can rely on automatic type deduction now without explicitly specifying the model type of the …
> add typing support to make and prepare

- tox-linter.ini
https://github.com/model-bakers/model_bakery/runs/4119324812?check_suite_focus=true
A python version mismatch led to tox job being silently skipped.
Not sure yet how to approach it to not have such issues in the future, but at least we can resolve this by fixing the version.
> CI: Use python 3.10 for linters

- CHANGELOG.md
- model_bakery/baker.py
`make`/`prepare`  now return the correct type depending on `_quantity`
> Improve type hinting

- CHANGELOG.md
- model_bakery/_types.py
- model_bakery/baker.py
- model_bakery/recipe.py
- tests/test_baker.py
- tests/test_filling_fields.py
- tests/test_recipes.py
Using generic types in ``model_bakery.recipe`` module allows for better hints from IDEs (if supported). Generic types are part of the stdlib's ``typing`` since 3.5, so the changes are conform with the range of Python versions currently supported by the library (although note that 3.5 and 3.6 are EOL already).
Sample code snippet:
```py
from django.db.models import Model, ForeignKey
from model_bakery.recipe import Recipe, foreign_key, related
class C(Model):
...
r = Recipe(C)
reveal_type(r)
reveal_type(r.extend(spam="eggs"))
reveal_type(r.make())
reveal_type(r.make(_quantity=None))
reveal_type(r.make(_quantity=100))
reveal_type(foreign_key(Recipe(C)))
reveal_type(related(r, r))
```
On current mainline, ``mypy`` will emit
```
test.py:14: note: Revealed type is "model_bakery.recipe.Recipe" …
```
> Better type hints for model_bakery.recipe

- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
Fixes #230
Pretty straightforward. It only updates the error messages to include the field name.
> Improve exception error message

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_baker.py
Fixes #291 
Given the way Django's `Model.save()` works, the code was breaking when trying to prepared (via `baker.prepare`) objects which hold FK for other prepared instances. The `save` call only persists the current model and not the subsequent ones. 
Meanwhile, django manager's `set` or `add` methods does handle nested persistence, but doesn't know how to save models which doesn't hold other FKs (or at least this is what I understood from the issue).
So, this PR introduces a fixes to only save an object before adding it to the related model if it doesn't have any FK. Other scenarios should now be handled by Django
> Get ManyToOneRel fields (reverse FK) back to work

- CHANGELOG.md
- model_bakery/random_gen.py
- tests/test_baker.py
I wrote a test in pytest that does:
```python
baker.prepare(SomeModel, _fill_optional=True)
```
and it failed with:
> RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it. 
model_bakery was trying to generate a ContentType value to fill in with and the first thing it does is to fetch a random value from the database:
```sh
path/to/venv/lib/python3.7/site-packages/model_bakery/random_gen.py:208: in gen_content_type
return ContentType.objects.get_for_model(choice(apps.get_models()))
```
The `gen_content_type()` function tries to remediate when database access is not available:
https://github.com/model-bakers/model_bakery/blob/1.4.0/model_bakery/random_gen.py#L207-L211
```python
try:
return …
```
> Fix random generation of ContentType values when there is no database access

- .github/workflows/tests.yml
- CHANGELOG.md
- setup.py
- tox.ini
2021-12-23 it reached end-of-life:
https://www.python.org/dev/peps/pep-0494/#lifespan
> Drop Python 3.6 support

- CHANGELOG.md
- docs/source/index.rst
- requirements.txt
- setup.py
- tox.ini
It reached end-of-life 2022-04-11:
https://www.djangoproject.com/download/#supported-versions
> Drop Django 2.2 support

- .github/workflows/changelog.yml
- CHANGELOG.md
... with a custom solution that can ignore Dependabot PRs.
Check still works, here is a first commit without a changelog:
https://github.com/model-bakers/model_bakery/actions/runs/2564748259
> Replace changelog reminder action

- CHANGELOG.md
- model_bakery/recipe.py
- tests/generic/baker_recipes.py
- tests/generic/models.py
- tests/test_recipes.py
PR #292 introduced explicit defaults for `make` and `prepare`,
which were then overwriting custom values in certain cases (explained in #308).
This PR attempts to fix this issue by not having explicit defaults.
> Fix #308 -- do not force defaults for `make` and `prepare`

- CHANGELOG.md
- model_bakery/timezone.py
- tests/test_utils.py
Make code compatible with future Django release.
```
model_bakery/timezone.py:6: RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.
from django.utils.timezone import utc
```
> fix future deprecate warning of django.utils.timezone.utc

- docs/source/conf.py
- tests/generic/models.py
There are small typos in:
- docs/source/conf.py
- tests/generic/models.py
Fixes:
- Should read `that` rather than `shat`.
- Should read `following` rather than `followin`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- CHANGELOG.md
- model_bakery/utils.py
- tests/test_utils.py
Fixes #322. Allows `seq` to properly increment from a timezone-aware starting datetime.
> [#322] Fix `seq` for timezone-aware start value

- .github/workflows/changelog.yml
- .github/workflows/linter.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
Extending logic of `_save_related_objs` that was added in #206.
This is optimized because of `bulk_create` use on through model, but it is still quite heavy on queries.
I had to switch to Ubuntu 22 in CI to upgrade default SQLite version which supports returning pks in bulk create operations.
> Fix #298 -- create m2m when using `_bulk_create=True`

- .github/dependabot.yml
- .github/workflows/linter.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- CHANGELOG.md
`model-bakery` was already supporting 3.11-dev, now we can switch to released 3.11.
PR also includes a couple of linting changes.
> CI: Switch to Python 3.11 release

- .github/workflows/ci.yml
tox 4 was released yesterday, and tox-py is incompatible with it. We can replace it with a one-liner as documented: https://github.com/adamchainz/tox-py#installation
- [n/a] [CHANGELOG.md](CHANGELOG.md) is updated
> Fix CI for tox 4

- CHANGELOG.md
- docs/source/how_bakery_behaves.rst
- model_bakery/generators.py
- requirements_dev.txt
- tests/generic/models.py
- tests/test_filling_fields.py
It was removed in Django 3.1 and we support Django 3.2+ only.
> Drop support for `FloatRangeField`

- CHANGELOG.md
- model_bakery/utils.py
- tests/test_utils.py
Fixes #415 
utils.seq(0, start=0) should start from 0
> fix: seq function with start=0

- CHANGELOG.md
- model_bakery/random_gen.py
- postgres-docker
- tests/generic/models.py
Fixes #407
Allows generating strings when `max_length=None`.
> Allow generating strings when max_length=None

- CHANGELOG.md
- Makefile
- model_bakery/baker.py
- model_bakery/random_gen.py
- tests/test_baker.py
- tests/test_filling_fields.py
Adds baker random generation seeding. This allows for repeatable random generation within baker fixtures independently of other packages/system random. Future support could be added to seed individual instances of baker (like [faker](https://github.com/joke2k/faker) does).
After merging this a follow up PR could add baker seeding to [pytest-randomly](https://github.com/pytest-dev/pytest-randomly).
Re issue https://github.com/model-bakers/model_bakery/issues/380.
> :sparkles: Adds global seeding to baker

- CHANGELOG.md
- model_bakery/baker.py
https://github.com/model-bakers/model_bakery/pull/352 was meant to be a cosmetic change which introduced a performance regression.
This PR reduces the time complexity of `get_fields()` from O(n*m) to O(n).
I have a project of significant size (over 50k tests), this change reduces the total runtime of the test suite by ~200% back to what we saw before release 1.8.0.
I also tried other approaches, for example using `filter` or turning this into a cached property but these didn't achieve a better result.
> perf: improve performance of `Baker.get_fields()`

- .pre-commit-config.yaml
- CHANGELOG.md
Previously, pre-commit was just showing ruff fixes, but not applying them, this changes the behaviour to fix and exit with error code.
> Bump pre-commit version, fix ruff caller

- .github/workflows/ci.yml
- CHANGELOG.md
Noted, that failing linters are preventing tests to run, which can block/slow down contributors.
> CI: remove hard requirement on linters for tests to run

- CHANGELOG.md
- model_bakery/random_gen.py
In the random_gen utility, the gen_slug and gen_string methods already return string values, rendering the additional casting operations unnecessary.
> refactor/perf: Eliminate redundant string casting in random_gen utility

- CHANGELOG.md
- pyproject.toml
- tox.ini
https://www.djangoproject.com/download/#supported-versions
https://endoflife.date/django
> Drop Django 4.1 support (reached end of life)

- .github/workflows/ci.yml
It seems like the v4 is still unreliable and fails with timeouts:
```
Attempt 1 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact. Retrying request in 3000 ms...
```
I am putting this on hold.
> Bump GitHub Actions artifacts to v4

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/content_types.py
- model_bakery/generators.py
- tests/conftest.py
- tests/generic/models.py
- tests/test_baker.py
- tests/test_filling_fields.py
- tox.ini
As mentioned in #265 - we are not hard-depending on `contenttypes` framework, so we need to be able to bake without it.
It is a bit tricky as there are multiple places, where we are using `contenttypes` framework and `auth` framework (which depends on `contenttypes`), however nothing is impossible.
> Fix #265 -- drop hard dependency on `contenttypes` framework

- model_bakery/recipe.py
Heyo, hopefully an easy one. We are using model bakery in a setting where the DB can have millions of rows and counting the table just for checking, if any entry exists is overkill. The easy solution: only check for existence.
> Replace expensive count() with cheap exists()

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/recipe.py
- tests/test_recipes.py
Fix `make_recipe` to work with `_quantity`. Fixes #28.
> Fix make_recipe to work with _quantity #28

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/content_types.py
- tests/test_filling_fields.py
A clear and concise description of what the change is.
> Refs #416 -- Allow combination of GFK and `_fill_optional`

- CHANGELOG.md
- model_bakery/baker.py
- pyproject.toml
- tox.ini
[Django 5.1 was released](https://docs.djangoproject.com/en/5.1/releases/5.1/).
<strike>
Amongst the changes, there is [a signature change of a generic foreign key](https://github.com/django/django/commit/6002df06713cb0a7050432263527a25754190c27), which needs to be covered.
</strike>
Okay, I figured the issue, it was an old bug described in https://github.com/model-bakers/model_bakery/issues/416. Now I finally understood the cause and provided a fix. And there is no changes in Django 5.1 that should be addressed separately in order to provide support.
> Fix #483 -- Add Django 5.1 support

- CHANGELOG.md
- model_bakery/baker.py
- model_bakery/content_types.py
- tests/test_filling_fields.py
Replace a hacky workaround from https://github.com/model-bakers/model_bakery/commit/0b4cfa7fe804bd74836aa3dff8141fbe24da500f#diff-7aca726c4b3af089805b51a56736cde676621ea8b404f024d8e51d879677ee09R17 with proper GFK field handling.
So now, the content type and object id should be filled from the provided content object.
> Fix #488 -- Align GFK and content type fields

- docs/how_bakery_behaves.md
- Update Custom Fields section in README
- Demonstrate how to use BAKER_CUSTOM_FIELDS_GEN in Django settings
> docs: Add Django settings example for custom field generators  

- model_bakery/baker.py
- tests/test_filling_fields.py
A clear and concise description of what the change is.
> Do not handle GFK fields when the object is None

- model_bakery/baker.py
- tests/test_filling_fields.py
Allows `None` within iterators for generic foreign keys. The test also confirms that `next` is called on the iterator.
> Allow None value for generic foreign keys within iterators

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_filling_fields.py
We don't want to set `content_type` and `object_id` fields to a random values in case where the `content_object` is None, but `_fill_optional=True`.
> Fix #498 -- Reset GFK fields when content object is `None`

- .github/workflows/ci.yml
Addressing breaking changes in GitHub Action:
https://github.com/actions/upload-artifact/releases/tag/v4.4.0
> Fix coverage artifact uploading

- CHANGELOG.md
- model_bakery/baker.py
- tests/generic/models.py
- tests/test_filling_fields.py
Closes https://github.com/model-bakers/model_bakery/issues/479
This PR changes the `Baker.generate_value` method to also consider the values configured in `Field.db_default`.
> Fix #479 -- Make sure `db_default` is being considered

- .github/workflows/ci.yml
- CHANGELOG.md
- pyproject.toml
- tox.ini
> Adds support to python 3.13

- model_bakery/recipe.py
- tests/test_baker.py
Fixed the error that when using `Recipe.prepare` the _quantity parameter was None
Error stack trace
```shell
tests/test_baker.py:292: in test_recipe_prepare_model_with_one_to_one_and_save_related
lonely_person = baker_recipes.lonely_person.prepare(_save_related=True)
model_bakery/recipe.py:175: in prepare
self._model, _using=_using, **self._mapping(_using, defaults)
model_bakery/recipe.py:72: in _mapping
for _ in range(_quantity)
E   TypeError: 'NoneType' object cannot be interpreted as an integer
```
> fix: Recipe prepare

- CHANGELOG.md
- model_bakery/timezone.py
- model_bakery/utils.py
Remove deprecation warning of datetime.datetime.utcfromtimestamp.
> Remove deprecation warning of datetime.datetime.utcfromtimestamp.

- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
> fix and test regression in 1.18.3 forbidding setting GFK by a function

- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
> fix and test regression in 1.19.3 forbidding setting GFK via proxy model

- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
- Issue: When `baker.make` with `_fill_optional` set as True, the values of those `DateTimeField` with `auto_now_add=True` or `auto_now=True` from the resulting instance are different from the value stored in DB.
- <details><summary>The test case from the first commit is to reproduce the issue</summary>
</details> 
- solution: skip the auto datetime fields
> fix: auto now fields should be skipped

- model_bakery/recipe.py
- tests/test_recipes.py
**Describe the problem**
If a recipe defines default values for list-based or dict-based fields (such as `JSONField` or `ArrayField`), the objects built from this recipe directly refer to these recipe defaults instead of holding their own copy of the data.
Therefore, any modifications on these fields affect the recipe "parent" attribute and all depending instances. In my opinion/experience, this behavior is unexpected and error prone.
**Note:** For other data types, the isolation between recipe and instances is already guaranteed, which is also an argument to apply the same behavior in all cases.
**Describe the proposed change**
With this change, every baked instance holds an isolated copy of the recipe default attributes of any Container class (e.g., `dict` or `list`). This prevents from …
> Isolate Recipe defaults to prevent modification via instances

- CHANGELOG.md
- model_bakery/baker.py
- tests/test_baker.py
- tests/test_recipes.py
Fix [#519](https://github.com/model-bakers/model_bakery/issues/519), which is a regression introduced in [#507](https://github.com/model-bakers/model_bakery/pull/507). 
- The auto now fields should be skipped in `_skip_field()`. Instead, assign the specified value to the resulting instance.
- Add test cases (modified from those provided by @hoefling in [#519](https://github.com/model-bakers/model_bakery/issues/519)).
> fix: should not skip auto now fields but assign with specified value

- Makefile
Run `make lint` would fail now since `ruff <path>` is obsoleted by `ruff check <path>`.
> fix: run `ruff check .` when `make lint`

- CHANGELOG.md
- tests/conftest.py
- tests/generic/models.py
A couple of leftover checks we could drop since [Django 4.2 is the minimally supported version](https://endoflife.date/django).
> Drop fallbacks made for Django < 4.2
